version: '3.8'

services:
  # 主节点 1
  redis-node1:
    image: redis:7
    container_name: redis-node1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf
    ports:
      - "7001:7001"
    volumes:
      - ./data/node1:/data
    networks:
      - redis-net

  # 主节点 2
  redis-node2:
    image: redis:7
    container_name: redis-node2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf
    ports:
      - "7002:7002"
    volumes:
      - ./data/node2:/data
    networks:
      - redis-net

  # 主节点 3
  redis-node3:
    image: redis:7
    container_name: redis-node3
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes-7003.conf
    ports:
      - "7003:7003"
    volumes:
      - ./data/node3:/data
    networks:
      - redis-net

  # 从节点 1
  redis-node4:
    image: redis:7
    container_name: redis-node4
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes-7004.conf
    ports:
      - "7004:7004"
    volumes:
      - ./data/node4:/data
    networks:
      - redis-net

  # 从节点 2
  redis-node5:
    image: redis:7
    container_name: redis-node5
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes-7005.conf
    ports:
      - "7005:7005"
    volumes:
      - ./data/node5:/data
    networks:
      - redis-net

  # 从节点 3
  redis-node6:
    image: redis:7
    container_name: redis-node6
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes-7006.conf
    ports:
      - "7006:7006"
    volumes:
      - ./data/node6:/data
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge